---
- name: Install the packages
  package: pkg={{ item }} state=installed
  with_items:
  - selinux-policy-{{ selinux_policy }}
  - policycoreutils-python
  # for debugging
  - setools-console

- name: Set state to enforcing
  shell: setenforce 1
  when: selinux_disabled is not defined and ansible_selinux.mode == 'permissive'

- name: Deploy configuration
  template: dest=/etc/selinux/{{ item }} src={{ item }}
  with_items:
  - config
  - semanage.conf
