---
- name: Install the packages
  package:
    pkg: "{{ item }}"
    state: "installed"
  with_items:
  - selinux-policy-{{ selinux_policy }}
  # for debugging
  - setools-console
  # to have proper logs (normaly installed by default but…)
  - audit
  - policycoreutils

- name: Install packages on older distribution
  package:
    pkg: "{{ item }}"
  with_items:
  - policycoreutils-python
  when: ansible_distribution_major_version|int < 8

- name: Install packages on recent distribution
  package:
    pkg: "{{ item }}"
  with_items:
  - policycoreutils-python-utils
  when: ansible_os_family == 'Fedora' or ansible_distribution_major_version|int >= 8

- name: Set state to enforcing
  command: setenforce 1
  when: selinux_disabled is not defined and ansible_selinux.mode == 'permissive'

- name: Deploy configuration
  template:
    dest: "/etc/selinux/{{ item }}"
    src: "{{ item }}"
  with_items:
  - config
  - semanage.conf

- name: Start auditd service
  service:
    name: auditd
    enabled: yes
    state: started

