---
- name: Install the packages
  package: pkg={{ item }} state=installed
  with_items:
  - selinux-policy-{{ selinux_policy }}
  - policycoreutils-python
  # for debugging
  - setools-console
  # to have proper logs (normaly installed by default but…)
  - audit
  - policycoreutils

- name: Install packages on recent distribution
  package:
    pkg: "{{ item }}"
    state: installed
  with_items:
  # for debugging
  - setools-console
  - policycoreutils-python
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version >= '6'

- name: Set state to enforcing
  shell: setenforce 1
  when: selinux_disabled is not defined and ansible_selinux.mode == 'permissive'

- name: Deploy configuration
  template: dest=/etc/selinux/{{ item }} src={{ item }}
  with_items:
  - config
  - semanage.conf

- name: start auditd service
  service:
    name: auditd
    enabled: yes
    state: started

